platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox

inputs:
  - name: rapidpro-docker

outputs:
  - name: image-params

params:
    version_suffix:

run:
  path: ./rapidpro-docker/.ci/build.sh
