resources:
- name: rapidpro-docker
  type: git
  source:
    uri: https://github.com/praekeltfoundation/rapidpro-docker
    branch: master
  webhook_token: prod-my-resource
  check_every: 30m

- name: rapidpro-image
  type: docker-image
  source:
    repository: praekeltfoundation/rapidpro
    username: {{rapidpro-dockerhub-username}}
    password: {{rapidpro-dockerhub-password}}
  check_every: 30m

jobs:
- name: build-image
  plan:
  - get: rapidpro-docker
    trigger: true
  - task: build
    file: rapidpro-docker/.ci/build.yml
    params:
        VERSION_SUFFIX: {{version-suffix}}
  - put: rapidpro-image
    params:
      build: rapidpro-docker
      tag: image-params/tag
      tag_as_latest: true
