apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-nginx
  namespace: example-rapidpro
  labels:
    deployment: example-nginx
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      deployment: example-nginx
  template:
    metadata:
      namespace: example-rapidpro
      labels:
        deployment: example-nginx
    spec:
      containers:
        - name: nginx
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
          # This image doesn't exist and should be replaced with one built
          # with a config for your deploy.
          # See the /nginx folder for a example of the config
          image: praekeltfoundation/example-nginx-prod:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  namespace: example-rapidpro
  name: example-nginx
spec:
  type: LoadBalancer
  selector:
    deployment: example-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
